services:

  dev:
    hostname: dev
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ..:/workspaces/LinuxNetwork
    cap_add:
      - NET_ADMIN
    command: ["sleep", "infinity"]

  mosquitto:
    hostname: mosquitto
    image: eclipse-mosquitto:latest
    volumes:
      - ../config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ../certs/ca.crt:/mosquitto/certs/ca.crt
      - ../certs/ca.key:/mosquitto/certs/ca.key
      - ../log:/mosquitto/log
    command: ["mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]